language: php

sudo: false

php:
- 7
- 5.2
- 5.3
- 5.4
- 5.5
- 5.6

env:
- WP_VERSION=latest

install:
- npm install grunt-cli
- npm install
  
before_script:
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
- WP_TESTS_DIR=/tmp/wordpress-tests-lib phpunit
